#!/usr/bin/env python3
"""Stage 7: open the weekly observatory PR.

NO LLM CALL — pure orchestration:
  - Stages the new files (cost-log update, new runs/<date>/*.json, report md, judge-flags.json)
  - Computes labels from flag count (zero → auto-merge-safe, any → needs-bryan)
  - Builds the PR title `observatory: weekly run YYYY-MM-DD (N flags)`
  - Builds the PR body from the rendered report
  - Shells out to `gh` CLI (simpler than threading peter-evans through the YAML)

In `--dry-run` mode: prints the planned `gh` invocations + body to stdout without
calling `git` or `gh`. Used by tests + by Bryan for local previews.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RUNS_DIR = REPO_ROOT / "data" / "observatory" / "runs"
DEFAULT_REPORTS_DIR = REPO_ROOT / "data" / "observatory" / "reports"
DEFAULT_COST_LOG = REPO_ROOT / "data" / "observatory" / "cost-log.json"
DEFAULT_JUDGE_FLAGS = REPO_ROOT / "data" / "observatory" / "judge-flags.json"

LABEL_AUTO_MERGE = "auto-merge-safe"
LABEL_NEEDS_BRYAN = "needs-bryan"
LABEL_BASE = ["observatory", "weekly-run"]


def count_run_flags(reports_dir: Path, run_id: str) -> int:
    report_path = reports_dir / f"{run_id}.md"
    if not report_path.exists():
        return 0
    text = report_path.read_text()
    # Count entries in the frontmatter sections we treat as actionable flags:
    # broken, top_movers (any |Δ|>=2 already filtered upstream), judge_flags.
    fm = _extract_frontmatter(text)
    flags = 0
    for k in ("broken", "top_movers", "judge_flags"):
        flags += _yaml_list_count(fm, k)
    return flags


def _extract_frontmatter(text: str) -> str:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    return m.group(1) if m else ""


def _yaml_list_count(fm: str, key: str) -> int:
    # Match top-level lines, then count subsequent "  - " entries until next top-level key.
    lines = fm.splitlines()
    n = 0
    in_block = False
    for line in lines:
        if not in_block:
            if line.startswith(f"{key}:"):
                in_block = True
        else:
            if line.startswith("  - "):
                n += 1
            elif line and not line.startswith(" "):
                break
    return n


def build_labels(flag_count: int) -> list[str]:
    labels = list(LABEL_BASE)
    labels.append(LABEL_AUTO_MERGE if flag_count == 0 else LABEL_NEEDS_BRYAN)
    return labels


def build_pr_body(run_id: str, reports_dir: Path, flag_count: int) -> str:
    report_path = reports_dir / f"{run_id}.md"
    body_parts = [
        f"Auto-generated observatory weekly run for **{run_id}**.",
        f"",
        f"**Flags raised this run:** {flag_count}",
        f"",
        f"---",
        f"",
    ]
    if report_path.exists():
        body_parts.append(report_path.read_text())
    body_parts.append("")
    body_parts.append("_Generated by `scripts/observatory/open_pr.py`._")
    return "\n".join(body_parts)


def run_cmd(cmd: list[str], *, cwd: Path | None = None, check: bool = True, env: dict[str, str] | None = None) -> subprocess.CompletedProcess:
    print(f"$ {shlex.join(cmd)}")
    return subprocess.run(cmd, cwd=cwd or REPO_ROOT, check=check, text=True, capture_output=True, env=env)


def stage_files(run_id: str) -> list[str]:
    """The set of file paths the PR will include."""
    rel_paths = [
        f"data/observatory/runs/{run_id}",
        f"data/observatory/reports/{run_id}.md",
        "data/observatory/cost-log.json",
        "data/observatory/judge-flags.json",
    ]
    return rel_paths


def open_pr(
    *,
    run_id: str,
    branch: str,
    title: str,
    body: str,
    labels: list[str],
    base: str = "main",
    dry_run: bool = False,
) -> int:
    files = stage_files(run_id)
    if dry_run:
        print("--- DRY RUN ---")
        print(f"branch: {branch}")
        print(f"title:  {title}")
        print(f"labels: {','.join(labels)}")
        print(f"base:   {base}")
        print("files to stage:")
        for p in files:
            print(f"  {p}")
        print("--- BODY ---")
        print(body)
        print("--- /DRY RUN ---")
        return 0

    # 1. Make sure git identity is set (GitHub Actions runners pass these via env;
    # set defaults if a local user runs it).
    env = os.environ.copy()
    env.setdefault("GIT_AUTHOR_NAME", "observatory-bot")
    env.setdefault("GIT_AUTHOR_EMAIL", "observatory@promptwritingstudio.com")
    env.setdefault("GIT_COMMITTER_NAME", env["GIT_AUTHOR_NAME"])
    env.setdefault("GIT_COMMITTER_EMAIL", env["GIT_AUTHOR_EMAIL"])

    # 2. Branch.
    run_cmd(["git", "checkout", "-B", branch], env=env)

    # 3. Stage + commit (allow paths that may not exist if zero flags / first run).
    for p in files:
        full = REPO_ROOT / p
        if full.exists():
            run_cmd(["git", "add", p], env=env)
    status = run_cmd(["git", "status", "--porcelain"], env=env).stdout.strip()
    if not status:
        print("no changes to commit; skipping PR")
        return 0
    run_cmd(["git", "commit", "-m", title], env=env)

    # 4. Push (force-with-lease in case the branch was reused — unlikely but safe).
    run_cmd(["git", "push", "--force-with-lease", "--set-upstream", "origin", branch], env=env)

    # 5. PR.
    pr_cmd = [
        "gh", "pr", "create",
        "--base", base,
        "--head", branch,
        "--title", title,
        "--body", body,
    ]
    for label in labels:
        pr_cmd.extend(["--label", label])
    run_cmd(pr_cmd, env=env)
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--run-id", required=True)
    p.add_argument("--reports-dir", type=Path, default=DEFAULT_REPORTS_DIR)
    p.add_argument("--branch", default=None)
    p.add_argument("--base", default="main")
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    branch = args.branch or f"observatory/run-{args.run_id}"
    flag_count = count_run_flags(args.reports_dir, args.run_id)
    title = f"observatory: weekly run {args.run_id} ({flag_count} flag{'s' if flag_count != 1 else ''})"
    body = build_pr_body(args.run_id, args.reports_dir, flag_count)
    labels = build_labels(flag_count)
    return open_pr(
        run_id=args.run_id,
        branch=branch,
        title=title,
        body=body,
        labels=labels,
        base=args.base,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    raise SystemExit(main())
